[tools]
hk = "latest"
pkl = "latest"
usage = "latest"
"pipx:catt" = "latest"
"pipx:qrcode" = "latest"
# https://github.com/kubernetes/kubernetes/issues/133864
kubectl = "1.34.1"

[env]
HK_MISE = true
