# Don't print a new line at the start of the prompt
add_newline = false

[line_break]
disabled = true

[aws]
symbol = " "

[battery]
disabled = true
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""

[cmd_duration]
disabled = true

[conda]
disabled = true
symbol = " "

[directory]
format = "[ $path]($style)[$read_only]($read_only_style) "
style = "bold blue"
truncation_length = 99
truncate_to_repo = false

[dotnet]
disabled = true

[docker_context]
disabled = true
symbol = " "

[elixir]
disabled = true
symbol = " "

[elm]
disabled = true
symbol = " "

[gcloud]
disabled = true

[git_branch]
format = "[$symbol$branch]($style) "
symbol = " "
style = "bold green"

[git_status]
style = "bold yellow"

[golang]
disabled = true
symbol = " "

[hg_branch]
symbol = " "

[java]
disabled = true
symbol = " "

[julia]
disabled = true
symbol = " "

[kubernetes]
disabled = true
format = '[$symbol$context( \($namespace\))]($style) '

[memory_usage]
disabled = true
symbol = " "

[nim]
disabled = true
symbol = " "

[nix_shell]
disabled = true
symbol = " "

[nodejs]
disabled = true
symbol = " "

[package]
disabled = true
symbol = " "

[php]
disabled = true
symbol = " "

[python]
disabled = true
symbol = " "

[ruby]
disabled = true
symbol = " "

[rust]
disabled = true
symbol = " "
