# Don't print a new line at the start of the prompt
add_newline = false

[line_break]
disabled = true

[aws]
symbol = " "

[battery]
disabled = true
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""

[cmd_duration]
disabled = true

[conda]
disabled = true
symbol = " "

[directory]
truncation_length = 99
truncate_to_repo = false

[dotnet]
disabled = true

[docker]
disabled = true
symbol = " "

[elixir]
disabled = true
symbol = " "

[elm]
disabled = true
symbol = " "

[git_branch]
symbol = " "
style = "bold green"

[git_status]
style = "bold yellow"
untracked_count.enabled = true
stashed_count.enabled = true
modified_count.enabled  = true
staged_count.enabled  = true
renamed_count.enabled = true
deleted_count.enabled = true

[golang]
disabled = true
symbol = " "

[haskell]
disabled = true
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
disabled = true
symbol = " "

[memory_usage]
disabled = true
symbol = " "

[nim]
disabled = true
symbol = " "

[nix_shell]
disabled = true
symbol = " "

[nodejs]
disabled = true
symbol = " "

[package]
disabled = true
symbol = " "

[php]
disabled = true
symbol = " "

[python]
disabled = true
symbol = " "

[ruby]
disabled = true
symbol = " "

[rust]
disabled = true
symbol = " "
