#!/usr/bin/env sh
# Usage: git-edit [conflict|staged|edited|commited]
# source: reddit

main() {
  action="$1"

  case $action in 
    conflict | conflicts | conflicted)
      $EDITOR $(git diff --name-only --diff-filter=U)
      ;;
    commited)
      $EDITOR $(git diff HEAD^ --name-only --diff-filter=ACMR)
      ;;
    staged)
      $EDITOR $(git diff --staged --name-only --diff-filter=ACMR)
      ;;
    status)
      $EDITOR $(git status --porcelain | awk '{print $2}')
      ;;
    edited)
      $EDITOR $(git diff HEAD --name-only --diff-filter=ACMR)
      ;;
  esac
}

main "$@"
