stages:
  - test

pacman:
  stage: test
  image: archlinux
  script:
    - echo 'Running pacman test script...'
    - pacman -Sy
    - chmod +x tests/pacman.test.py
    - python3 tests/pacman.test.py
