keys:
  - &zenix age1uzwgfr26gd9eus80ydsskdkp4gh6az5vr78cvd6zzamh35snz4hq5x3whm
  - &xps15 age1rgxuzyrc8px3ynsusmnjdsvn3suvgj7ep6re9lvh2vlqkv445skqxz4jed
  - &e470 age17kk48hynzgad60c8vdaf5phg8k9563r6mhezzhgngl3hyxrgea5q225656
creation_rules:
  - path_regex: hosts\/\w*\/secrets\.yaml
    key_groups:
    - age:
      - *zenix
      - *xps15
      - *e470
