#!/bin/bash

path=$(fd --type=d --hidden --no-ignore ".git" --exclude node_modules --exclude tmp --absolute-path "$HOME/Projects" | grep ".git/" | sd "/.git/" "" | fzf)
if [ "$path" != "" ]; then
  pname=$(basename "$path")
  path="/home/clemens/Projects/$pname"

  if [[ -n $ZELLIJ ]]; then
    zellij action new-tab --cwd "$path" --name "$pname" --layout dev
  elif [[ -n $WEZTERM_PANE ]]; then
    new_pane=$(wezterm cli spawn --cwd "$path" -- zsh -c "distrobox-enter main")
    wezterm cli set-tab-title "$pname" --pane-id "$new_pane"
    wezterm cli split-pane --pane-id "$new_pane" --bottom --cells 18 --cwd "$path"
    wezterm cli activate-pane --pane-id "$new_pane"
    printf "nvim\n" | wezterm cli send-text --pane-id "$new_pane" --no-paste
  else
    cd "$path" || exit 1
  fi
fi
