#!/bin/bash

if [[ -n $ZELLIJ ]]; then
  if [[ -n $DIRENV_FILE ]]; then
    zj=$(which zellij)
    direnv exec "$zj" run -c -- lazygit && direnv exec "$zj" action toggle-fullscreen
  else
    zellij run -c -- lazygit && zellij action toggle-fullscreen
  fi
elif [[ -n $WEZTERM_PANE ]]; then
    wezterm cli zoom-pane --pane-id "$(wezterm cli split-pane -- zsh -c "distrobox-enter main -- zsh -c 'source ~/.zshrc && lazygit'")"
else
  lazygit
fi
