#!/bin/bash

if [[ -n $ZELLIJ ]]; then
  if [[ -n $DIRENV_FILE ]]; then
    zj=$(which zellij)
    direnv exec "$zj" run -c -- lazygit && direnv exec "$zj" action toggle-fullscreen
  else
    zellij run -c -- lazygit && zellij action toggle-fullscreen
  fi
else
  lazygit
fi
