# https://kind.sigs.k8s.io/docs/user/rootless
[containers]
pids_limit = -1

# https://github.com/containers/podman/issues/5488
[engine]
static_dir = "$HOME/.local/share/containers/storage/libpod"
volume_path = "$HOME/.local/share/containers/storage/libpod"
