#!/bin/bash

if [[ -n $WEZTERM_PANE ]]; then
  wezterm cli zoom-pane --pane-id "$(wezterm cli split-pane --percent 1 -- distrobox-enter main -e lazygit)"
else
  if command -v lazygit &> /dev/null; then
    lazygit
  fi
fi
