# Configuration for Alacritty, the GPU enhanced terminal emulator.

# Import additional configuration files
#
# Imports are loaded in order, skipping all missing files, with the importing
# file being loaded last. If a field is already present in a previous import, it
# will be replaced.
#
# All imports must either be absolute paths starting with `/`, or paths relative
# to the user's home directory starting with `~/`.
#import:
#  - /path/to/alacritty.yml

env:
  TERM: xterm-256color

window:
  dimensions:
    columns: 135
    lines: 35
  padding:
    x: 3
    y: 3
  decorations: full
  startup_mode: Windowed
  dynamic_title: true

scrolling:
  history: 15000
  multiplier: 3

font:
  normal:
    family: FiraCode Nerd Font
    style: Light
  bold:
    family: FiraCode Nerd Font
    style: Medium
  italic:
    family: FiraCode Nerd Font
  bold_italic:
    family: FiraCode Nerd Font
  size: 12.0
  offset:
    x: 0
    y: 0
  glyph_offset:
    x: 0
    y: 0
  use_thin_strokes: false

colors:
  primary:
    background: '#161b22'
    foreground: '#abb2bf'
  cursor:
    background: '#161b22'
    foreground: '#abb2bf'
  normal:
    black:   '#161b22'
    red:     '#e06c75'
    green:   '#98c379'
    yellow:  '#e5c07b'
    blue:    '#61afef'
    magenta: '#c678dd'
    cyan:    '#56b6c2'
    white:   '#737373'
  bright:
    black:   '#555555'
    red:     '#e06c75'
    green:   '#98c379'
    yellow:  '#e5c07b'
    blue:    '#61afef'
    magenta: '#c678dd'
    cyan:    '#56b6c2'
    white:   '#abb2bf'

bell:
  duration: 0

background_opacity: 1.0

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"
  save_to_clipboard: true

cursor:
  style:
    shape: Block
    blinking: Off
  unfocused_hollow: true

live_config_reload: true
alt_send_esc: true

mouse:
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }
  hide_when_typing: true

mouse_bindings:
 - { mouse: Middle, action: PasteSelection }

key_bindings:
  - { key: D,        mods: Shift|Control,   action: None               }
  - { key: N,        mods: Command,         action: SpawnNewInstance   }
  - { key: Space,    mods: Alt,             chars: " "                    }
  - { key: Back,     mods: Super,           chars: "\x15"                        } # delete word/line
  - { key: Left,     mods: Alt,             chars: "\x1bb"                     } # one word left
  - { key: Right,    mods: Alt,             chars: "\x1bf"                     } # one word right
  - { key: Left,     mods: Command,         chars: "\x1bOH",   mode: AppCursor } # Home
  - { key: Right,    mods: Command,         chars: "\x1bOF",   mode: AppCursor } # End
  # fuck macOS https://github.com/alacritty/alacritty/issues/458
  - { key: V,        mods: Command, action: Paste                      }
  - { key: C,        mods: Command, action: Copy                       }
  - { key: Q,        mods: Command, action: Quit                       }
  - { key: W,        mods: Command, action: Quit                       }
  - { key: L,        mods: Alt,     chars: "\x40"                      }
  - { key: Key5,     mods: Alt,        chars: "\x5b"                   }
  - { key: Key6,     mods: Alt,        chars: "\x5d"                   }
  - { key: Key7,     mods: Alt|Shift,  chars: "\x5c"                   }
  - { key: Key7,     mods: Alt,        chars: "\x7c"                   }
  - { key: Key8,     mods: Alt,        chars: "\x7b"                   }
  - { key: Key9,     mods: Alt,        chars: "\x7d"                   }
  - { key: N,        mods: Alt,     chars: "\x7E"                      }
  - { key: Caret,                   chars: "\x5e"                      }
  - { key: Equals,                  chars: "+"                      }
  - { key: Equals,   mods: Shift,   chars: "="                         }
  - { key: 28,      mods: Alt, chars: "{" }
  - { key: 25,      mods: Alt, chars: "}" }
  - { key: 37,      mods: Alt, chars: "@" }
  - { key: 26,      mods: Alt|Shift, chars: "\\" }
  - { key: 26,      mods: Alt, chars: "|" }
  - { key: 45,      mods: Alt, chars: "~" }
  - { key: 23,      mods: Alt, chars: "[" }
  - { key: 22,      mods: Alt, chars: "]" }
