---
name: renovate
on:
  schedule:
    - cron: '0 3 * * *'
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Renovate
        uses: renovatebot/github-action@531c6786d6cf05ef148c4cfe251745c2c6de442c # v41.0.9
        with:
          configurationFile: renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
