---
name: renovate
on:
  schedule:
    - cron: '0 3 * * *'
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Renovate
        uses: renovatebot/github-action@630a255a1f2f56c8d8ce160bed3e3ca577ca53e2 # v40.2.7
        with:
          configurationFile: renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
