---
name: renovate
on:
  schedule:
    - cron: '0 3 * * *'
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Renovate
        uses: renovatebot/github-action@a1ed1d0adddfdf138192d1fbe3150a80094dee6a # v40.3.1
        with:
          configurationFile: renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
