---
name: update-nixpkgs-lock
on:
  workflow_dispatch:
  schedule:
    # https://github.com/orgs/community/discussions/13454
    - cron: '30 0 * * THU'
jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v7
      - name: Update lockfile
        id: update
        uses: DeterminateSystems/update-flake-lock@v20
        with:
          pr-title: "chore: update flake"
          token: ${{ secrets.UPDATE_FLAKE_TOKEN }}
          pr-assignees: clemak27
          commit-msg: "chore: update nixpkgs"
          git-author-name: 'clemak27'
          git-author-email: 'clemak27@mailbox.org'
          git-committer-name: 'clemak27'
          git-committer-email: 'clemak27@mailbox.org'
          inputs: nixpkgs nixpkgs-stable home-manager sops-nix pre-commit-hooks nix-index-database
      - name: automerge
        run: gh pr merge --rebase --auto "${{ steps.update.outputs.pull-request-number }}"
        env:
          GH_TOKEN: ${{ secrets.UPDATE_FLAKE_TOKEN }}
